apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zt83ssobw-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zt83ssobw-go 
  name: zt83ssobw-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zt83ssobw-go 
